### PR TITLE
Retain big icons as an option

### PR DESCRIPTION
**Pull request by djr7m**
I noticed the commit history and thought I'd save the old big icons as a theme option. I symbolically linked the theme file and merged to tip-of-master to get all the other updates.

### CODE REVIEW

**Comment by benwoody** [comment]
I'm not really sure I see the point of including the large icons. They just take up space and make it impossible to select from in the drop down.

**Comment by djr7m** [comment]
Well, I suppose I could retain a seperate copy of the theme file and give it a different name to allow selection through the menu. That would mean linking two different folders to keep both options listed. Its only taking up space if you download / keep the extra copy. If you clone the repo you've got both copies already downloaded.

**Comment by djr7m** [comment]
Just a feature idea. may not be worth it. I had fun seeing the large octocat in my pidgin window :)

**Comment by benwoody** [comment]
This would also have to be updated in the rake file. 

I'm just not sure I see the need for large images in pidgin.  Looking at a few other themes, this doesn't seem to be something that is really used or implemented.

`I had fun seeing the large octocat in my pidgin window :)` - aaaalmost makes me want to merge this :wink:

**Pull request closed without merging**
